version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  flume:
    build:
      context: .
    # Replace this with the agent you want to run
    command: "spool_to_kafka.conf spool_agent"
    # Used for spool directory tests
    volumes:
      - .flume_spool:/.flume_spool
    depends_on:
      - kafka

  # kafka-consumer:
  #   image: bitnami/kafka
  #   command: kafka-console-consumer.sh --bootstrap-server zookeeper:2181 --topic flume_spool --from-beginning
  #   environment:
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #   depends_on:
  #     - flume
